// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BiofalsaDocumentDataSlicesSlice = BioFalsaSlice;

/**
 * Content for BioFalsa documents
 */
interface BiofalsaDocumentData {
  /**
   * Slice Zone field in *BioFalsa*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: biofalsa.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BiofalsaDocumentDataSlicesSlice>;
}

/**
 * BioFalsa document from Prismic
 *
 * - **API ID**: `biofalsa`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BiofalsaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BiofalsaDocumentData>,
    "biofalsa",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = HeroHomeSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type ImpostazioniDocumentDataSlicesSlice = never;

/**
 * Content for Impostazioni documents
 */
interface ImpostazioniDocumentData {
  /**
   * `slices` field in *Impostazioni*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: impostazioni.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ImpostazioniDocumentDataSlicesSlice>;
}

/**
 * Impostazioni document from Prismic
 *
 * - **API ID**: `impostazioni`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImpostazioniDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ImpostazioniDocumentData>,
    "impostazioni",
    Lang
  >;

export type AllDocumentTypes =
  | BiofalsaDocument
  | HomepageDocument
  | ImpostazioniDocument;

/**
 * Item in *BioFalsa → Default → Primary → Bio*
 */
export interface BioFalsaSliceDefaultPrimaryBioItem {
  /**
   * Frase field in *BioFalsa → Default → Primary → Bio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_falsa.default.primary.bio[].frase
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  frase: prismic.KeyTextField;

  /**
   * Accento field in *BioFalsa → Default → Primary → Bio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_falsa.default.primary.bio[].accento
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accento: prismic.KeyTextField;

  /**
   * Punto dopo field in *BioFalsa → Default → Primary → Bio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: bio_falsa.default.primary.bio[].punto_dopo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  punto_dopo: prismic.BooleanField;
}

/**
 * Primary content in *BioFalsa → Default → Primary*
 */
export interface BioFalsaSliceDefaultPrimary {
  /**
   * Bio field in *BioFalsa → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_falsa.default.primary.bio[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  bio: prismic.GroupField<Simplify<BioFalsaSliceDefaultPrimaryBioItem>>;

  /**
   * FotoFalsaBuona field in *BioFalsa → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_falsa.default.primary.fotofalsabuona
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fotofalsabuona: prismic.ImageField<never>;

  /**
   * FotoFalsaCattiva field in *BioFalsa → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_falsa.default.primary.fotofalsacattiva
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fotofalsacattiva: prismic.ImageField<never>;
}

/**
 * Default variation for BioFalsa Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioFalsaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BioFalsaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BioFalsa*
 */
type BioFalsaSliceVariation = BioFalsaSliceDefault;

/**
 * BioFalsa Shared Slice
 *
 * - **API ID**: `bio_falsa`
 * - **Description**: BioFalsa
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioFalsaSlice = prismic.SharedSlice<
  "bio_falsa",
  BioFalsaSliceVariation
>;

/**
 * Item in *HeroHome → Default → Primary → Elenco lista*
 */
export interface HeroHomeSliceDefaultPrimaryElencoListaItem {
  /**
   * Bullet point field in *HeroHome → Default → Primary → Elenco lista*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.elenco_lista[].bullet_point
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bullet_point: prismic.KeyTextField;
}

/**
 * Primary content in *HeroHome → Default → Primary*
 */
export interface HeroHomeSliceDefaultPrimary {
  /**
   * Titolo Hero field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.titolo_hero
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titolo_hero: prismic.RichTextField;

  /**
   * Testo hero field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.testo_hero
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testo_hero: prismic.RichTextField;

  /**
   * Sfondo Hero field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.sfondo_hero
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  sfondo_hero: prismic.ImageField<never>;

  /**
   * Gfi stella field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.gfi_stella
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gfi_stella: prismic.ImageField<never>;

  /**
   * Testo lista field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.testo_lista
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_lista: prismic.KeyTextField;

  /**
   * Elenco lista field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.elenco_lista[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  elenco_lista: prismic.GroupField<
    Simplify<HeroHomeSliceDefaultPrimaryElencoListaItem>
  >;
}

/**
 * Default variation for HeroHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroHome*
 */
type HeroHomeSliceVariation = HeroHomeSliceDefault;

/**
 * HeroHome Shared Slice
 *
 * - **API ID**: `hero_home`
 * - **Description**: HeroHome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHomeSlice = prismic.SharedSlice<
  "hero_home",
  HeroHomeSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BiofalsaDocument,
      BiofalsaDocumentData,
      BiofalsaDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      ImpostazioniDocument,
      ImpostazioniDocumentData,
      ImpostazioniDocumentDataSlicesSlice,
      AllDocumentTypes,
      BioFalsaSlice,
      BioFalsaSliceDefaultPrimaryBioItem,
      BioFalsaSliceDefaultPrimary,
      BioFalsaSliceVariation,
      BioFalsaSliceDefault,
      HeroHomeSlice,
      HeroHomeSliceDefaultPrimaryElencoListaItem,
      HeroHomeSliceDefaultPrimary,
      HeroHomeSliceVariation,
      HeroHomeSliceDefault,
    };
  }
}
