// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  barra_honest: dynamic(() => import("./BarraHonest")),
  bio_falsa: dynamic(() => import("./BioFalsa")),
  bio_vera: dynamic(() => import("./BioVera")),
  cose_non_piacciono: dynamic(() => import("./CoseNonPiacciono")),
  cose_piacciono: dynamic(() => import("./CosePiacciono")),
  hero_home: dynamic(() => import("./HeroHome")),
};
