// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bio_falsa: dynamic(() => import("./BioFalsa")),
  hero_home: dynamic(() => import("./HeroHome")),
};
